create unlogged table if not exists ${NWIS_WS_STAR_SCHEMA_NAME}.int_sitefile
(nwis_host_nm                   character varying (42)
,db_no                          character varying (6)
,agency_cd                      character varying (15)
,site_no                        character varying (45)
,station_nm                     character varying (150)
,station_ix                     character varying (150)
,lat_va                         character varying (33)
,long_va                        character varying (36)
,dec_lat_va                     decimal
,dec_long_va                    decimal
,coord_meth_cd                  character varying (3)
,coord_acy_cd                   character varying (3)
,coord_datum_cd                 character varying (30)
,district_cd                    character varying (9)
,land_net_ds                    character varying (69)
,map_nm                         character varying (60)
,country_cd                     character varying (6)
,state_cd                       character varying (6)
,county_cd                      character varying (9)
,mcd_cd                         character varying (15)
,map_scale_fc                   character varying (21)
,alt_va                         character varying (24)
,alt_meth_cd                    character varying (3)
,alt_acy_va                     character varying (9)
,alt_datum_cd                   character varying (30)
,huc_cd                         character varying (48)
,agency_use_cd                  character varying (3)
,basin_cd                       character varying (6)
,site_tp_cd                     character varying (21)
,topo_cd                        character varying (3)
,data_types_cd                  character varying (90)
,instruments_cd                 character varying (90)
,site_rmks_tx                   character varying (150)
,inventory_dt                   character varying (24)
,drain_area_va                  character varying (24)
,contrib_drain_area_va          character varying (24)
,tz_cd                          character varying (18)
,local_time_fg                  character varying (3)
,gw_file_cd                     character varying (90)
,construction_dt                character varying (24)
,reliability_cd                 character varying (3)
,aqfr_cd                        character varying (24)
,nat_aqfr_cd                    character varying (30)
,site_use_1_cd                  character varying (3)
,site_use_2_cd                  character varying (3)
,site_use_3_cd                  character varying (3)
,water_use_1_cd                 character varying (3)
,water_use_2_cd                 character varying (3)
,water_use_3_cd                 character varying (3)
,nat_water_use_cd               character varying (6)
,aqfr_type_cd                   character varying (3)
,well_depth_va                  character varying (24)
,hole_depth_va                  character varying (24)
,depth_src_cd                   character varying (3)
,project_no                     character varying (36)
,site_web_cd                    character varying (3)
,site_cn                        character varying (312)
,site_cr                        timestamp(6)
,site_mn                        character varying (312)
,site_md                        timestamp(6)
,deprecated_fg                  character varying (3)
,site_ld                        timestamp(6)
) with (fillfactor = 100);
