create unlogged table if not exists ${NWIS_WS_STAR_SCHEMA_NAME}.int_qw_sample
(nwis_host_nm                   character varying (42)
,db_no                          character varying (6)
,record_no                      character varying (24)
,agency_cd                      character varying (15)
,site_no                        character varying (45)
,site_db_no                     character varying (6)
,medium_cd                      character varying (9)
,sample_start_dt                timestamp(6)
,sample_start_sg                character varying (3)
,sample_start_tz_cd             character varying (18)
,sample_start_local_tm_fg       character varying (3)
,sample_end_dt                  timestamp(6)
,sample_end_sg                  character varying (3)
,sample_end_tz_cd               character varying (18)
,sample_end_local_tm_fg         character varying (3)
,sample_start_local_disp_fm     character varying (57)
,sample_start_utc_disp_fm       character varying (57)
,sample_end_local_disp_fm       character varying (57)
,sample_end_utc_disp_fm         character varying (57)
,local_tz_cd                    character varying (18)
,tm_datum_rlblty_cd             character varying (3)
,sample_id                      integer
,anl_stat_cd                    character varying (3)
,hyd_cond_cd                    character varying (3)
,samp_type_cd                   character varying (3)
,hyd_event_cd                   character varying (3)
,project_cd                     character varying (27)
,aqfr_cd                        character varying (24)
,lab_no                         character varying (21)
,tu_id                          integer
,body_part_id                   integer
,coll_ent_cd                    character varying (24)
,sidno_party_cd                 character varying (9)
,sample_cn                      character varying (312)
,sample_cr                      timestamp(6)
,sample_mn                      character varying (312)
,sample_md                      timestamp(6)
,sample_lab_cm_tx               character varying (4000)
,sample_lab_cm_cn               character varying (312)
,sample_lab_cm_cr               timestamp(6)
,sample_lab_cm_mn               character varying (312)
,sample_lab_cm_md               timestamp(6)
,sample_field_cm_tx             character varying (4000)
,sample_field_cm_cn             character varying (312)
,sample_field_cm_cr             timestamp(6)
,sample_field_cm_mn             character varying (312)
,sample_field_cm_md             timestamp(6)
,sample_web_cd                  character varying (3)
,deprecated_fg                  character varying (3)
,sample_ld                      timestamp(6)
) with (fillfactor = 100);
