CREATE USER NWIS_WS_STAR
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE WQP
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for NWIS_WS_STAR 
  GRANT CONNECT TO NWIS_WS_STAR;
  GRANT RESOURCE TO NWIS_WS_STAR;
  ALTER USER NWIS_WS_STAR DEFAULT ROLE ALL;
  -- 11 System Privileges for NWIS_WS_STAR 
  GRANT CREATE DATABASE LINK TO NWIS_WS_STAR;
  GRANT CREATE MATERIALIZED VIEW TO NWIS_WS_STAR;
  GRANT CREATE PUBLIC SYNONYM TO NWIS_WS_STAR;
  GRANT CREATE SEQUENCE TO NWIS_WS_STAR;
  GRANT CREATE SESSION TO NWIS_WS_STAR;
  GRANT CREATE SYNONYM TO NWIS_WS_STAR;
  GRANT CREATE TABLE TO NWIS_WS_STAR;
  GRANT CREATE VIEW TO NWIS_WS_STAR;
  GRANT QUERY REWRITE TO NWIS_WS_STAR;
  GRANT SELECT ANY TABLE TO NWIS_WS_STAR;
  GRANT UNLIMITED TABLESPACE TO NWIS_WS_STAR;
  -- 1 Tablespace Quota for NWIS_WS_STAR 
  ALTER USER NWIS_WS_STAR QUOTA UNLIMITED ON WQP;