create unlogged table if not exists ${NWIS_SCHEMA_NAME}.time_series_description
(time_series_description_id              integer generated by default as identity (start with 1)
,time_series_unique_id                   character varying (32)
,monitoring_location_id                  integer
,monitoring_location_identifier          character varying (21)
,unit                                    text
,label                                   text
,comment                                 text
,publish                                 boolean
,parameter                               text
,utc_offset                              smallint
,identifier                              text
,raw_end_time                            timestamp with time zone
,corrected_end_time                      timestamp with time zone
,raw_start_time                          timestamp with time zone
,corrected_start_time                    timestamp with time zone
,thresholds                              jsonb
,description                             text
,last_modified                           timestamp with time zone
,time_series_type                        text
,utc_offset_iso_duration                 text
,computation_identifier                  text
,sub_location_identifier                 text
,computation_preiod_identifier           text
,extended_attributes                     jsonb
,primary key (time_series_description_id)
,constraint time_series_description_ak unique (time_series_unique_id)
)
