create unlogged table if not exists ${NWIS_WS_STAR_SCHEMA_NAME}.int_qw_result
(nwis_host_nm        character varying (42)
,db_no               character varying (6)
,record_no           character varying (24)
,parm_cd             character varying (15)
,meth_cd             character varying (15)
,result_va           double precision
,result_va_tx        character varying (60)
,result_sg           character varying (3)
,result_rd           character varying (3)
,remark_cd           character varying (3 )
,rpt_lev_va          double precision
,rpt_lev_va_tx       character varying (60)
,rpt_lev_sg          character varying (3)
,rpt_lev_cd          character varying (18 )
,result_rnd_va       double precision
,result_rnd_va_tx    character varying (60)
,remark_rnd_cd       character varying (3)
,dqi_cd              character varying (3)
,null_val_qual_cd    character varying (3)
,prep_set_no         character varying (36)
,prep_dt             date
,anl_set_no          character varying (36)
,anl_dt              date
,lab_std_dev_va      double precision
,lab_std_dev_va_tx   character varying (60)
,lab_std_dev_sg      character varying (3)
,anl_ent_cd          character varying (24)
,val_qual_cd_tx      character varying (9)
,result_cn           character varying (312)
,result_cr           timestamp(6)
,result_mn           character varying (312)
,result_md           timestamp(6)
,result_lab_cm_tx    character varying (4000)
,result_lab_cm_cn    character varying (312)
,result_lab_cm_cr    timestamp(6)
,result_lab_cm_mn    character varying (312)
,result_lab_cm_md    timestamp(6)
,result_field_cm_tx  character varying (4000)
,result_field_cm_cn  character varying (312)
,result_field_cm_cr  timestamp(6)
,result_field_cm_mn  character varying (312)
,result_field_cm_md  timestamp(6)
,result_web_cd       character varying (3)
,result_ld           timestamp(6)
,deprecated_fg       character varying (3)
) with (fillfactor = 100);
