create unlogged table if not exists ${NWIS_WS_STAR_SCHEMA_NAME}. county
(country_cd                     character varying (2)
,state_cd                       character varying (2)
,county_cd                      character varying (3)
,county_nm                      character varying (48)
,county_max_lat_va              character varying (11)
,county_min_lat_va              character varying (11)
,county_max_long_va             character varying (12)
,county_min_long_va             character varying (12)
,county_max_alt_va              character varying (8)
,county_min_alt_va              character varying (8)
,county_md                      character varying (8)
,constraint county_pk
  primary key (country_cd, state_cd, county_cd)
) with (fillfactor = 100)
