create table int_sitefile
(nwis_host_nm                   varchar2(42 char)
,db_no                          varchar2(6 char)
,agency_cd                      varchar2(15 char)
,site_no                        varchar2(45 char)
,station_nm                     varchar2(150 char)
,station_ix                     varchar2(150 char)
,lat_va                         varchar2(33 char)
,long_va                        varchar2(36 char)
,dec_lat_va                     float(53)
,dec_long_va                    float(53)
,coord_meth_cd                  varchar2(3 char)
,coord_acy_cd                   varchar2(3 char)
,coord_datum_cd                 varchar2(30 char)
,district_cd                    varchar2(9 char)
,land_net_ds                    varchar2(69 char)
,map_nm                         varchar2(60 char)
,country_cd                     varchar2(6 char)
,state_cd                       varchar2(6 char)
,county_cd                      varchar2(9 char)
,mcd_cd                         varchar2(15 char)
,map_scale_fc                   varchar2(21 char)
,alt_va                         varchar2(24 char)
,alt_meth_cd                    varchar2(3 char)
,alt_acy_va                     varchar2(9 char)
,alt_datum_cd                   varchar2(30 char)
,huc_cd                         varchar2(48 char)
,agency_use_cd                  varchar2(3 char)
,basin_cd                       varchar2(6 char)
,site_tp_cd                     varchar2(21 char)
,topo_cd                        varchar2(3 char)
,data_types_cd                  varchar2(90 char)
,instruments_cd                 varchar2(90 char)
,site_rmks_tx                   varchar2(150 char)
,inventory_dt                   varchar2(24 char)
,drain_area_va                  varchar2(24 char)
,contrib_drain_area_va          varchar2(24 char)
,tz_cd                          varchar2(18 char)
,local_time_fg                  varchar2(3 char)
,gw_file_cd                     varchar2(90 char)
,construction_dt                varchar2(24 char)
,reliability_cd                 varchar2(3 char)
,aqfr_cd                        varchar2(24 char)
,nat_aqfr_cd                    varchar2(30 char)
,site_use_1_cd                  varchar2(3 char)
,site_use_2_cd                  varchar2(3 char)
,site_use_3_cd                  varchar2(3 char)
,water_use_1_cd                 varchar2(3 char)
,water_use_2_cd                 varchar2(3 char)
,water_use_3_cd                 varchar2(3 char)
,nat_water_use_cd               varchar2(6 char)
,aqfr_type_cd                   varchar2(3 char)
,well_depth_va                  varchar2(24 char)
,hole_depth_va                  varchar2(24 char)
,depth_src_cd                   varchar2(3 char)
,project_no                     varchar2(36 char)
,site_web_cd                    varchar2(3 char)
,site_cn                        varchar2(312 char)
,site_cr                        timestamp(6)
,site_mn                        varchar2(312 char)
,site_md                        timestamp(6)
,deprecated_fg                  varchar2(3 char)
,site_ld                        timestamp(6)
) parallel 4 compress pctfree 0 nologging;
