create table if not exists ${NWIS_SCHEMA_NAME}.network_site_rel
(network_site_rel_id                     integer generated by default as identity (start with 1)
,network_id                              integer
,monitoring_location_id                  integer
,primary key (network_site_rel_id )
,constraint network_mon_loc_uk unique (network_id, monitoring_location_id)
);