create unlogged table if not exists ${NWIS_SCHEMA_NAME}.nawqa_sites
(nwis_host_nm                   character varying (14)
,db_no                          character varying (2)
,agency_cd                      character varying (5)
,site_no                        character varying (15)
,station_nm                     character varying (50)
,station_ix                     character varying (50)
,lat_va                         character varying (11)
,long_va                        character varying (12)
,dec_lat_va                     character varying (40)
,dec_long_va                    character varying (40)
,coord_meth_cd                  character varying (1)
,coord_acy_cd                   character varying (1)
,coord_datum_cd                 character varying (10)
,district_cd                    character varying (3)
,land_net_ds                    character varying (23)
,map_nm                         character varying (20)
,country_cd                     character varying (2)
,state_cd                       character varying (2)
,county_cd                      character varying (3)
,mcd_cd                         character varying (5)
,map_scale_fc                   character varying (7)
,alt_va                         character varying (8)
,alt_meth_cd                    character varying (1)
,alt_acy_va                     character varying (3)
,alt_datum_cd                   character varying (10)
,huc_cd                         character varying (16)
,agency_use_cd                  character varying (1)
,basin_cd                       character varying (2)
,site_tp_cd                     character varying (7)
,topo_cd                        character varying (1)
,data_types_cd                  character varying (30)
,instruments_cd                 character varying (30)
,site_rmks_tx                   character varying (50)
,inventory_dt                   character varying (8)
,drain_area_va                  character varying (8)
,contrib_drain_area_va          character varying (8)
,tz_cd                          character varying (6)
,local_time_fg                  boolean
,gw_file_cd                     character varying (30)
,construction_dt                character varying (8)
,reliability_cd                 character varying (1)
,aqfr_cd                        character varying (8)
,nat_aqfr_cd                    character varying (10)
,site_use_1_cd                  character varying (1)
,site_use_2_cd                  character varying (1)
,site_use_3_cd                  character varying (1)
,water_use_1_cd                 character varying (1)
,water_use_2_cd                 character varying (1)
,water_use_3_cd                 character varying (1)
,nat_water_use_cd               character varying (2)
,aqfr_type_cd                   character varying (1)
,well_depth_va                  character varying (8)
,hole_depth_va                  character varying (8)
,depth_src_cd                   character varying (1)
,project_no                     character varying (12)
,site_web_cd                    character varying (1)
,site_cn                        character varying (104)
,site_cr                        timestamp(6)        not null
,site_mn                        character varying (104)
,site_md                        timestamp(6)        not null
,deprecated_fg                  boolean
,site_ld                        character varying (40)
,nawqa_site_fg                  boolean
,nasqan_nmn_site_fg             boolean
) with (fillfactor = 100);
