create unlogged table if not exists ${NWIS_SCHEMA_NAME}.discrete_ground_water
(monitoring_location_id                  integer
,agency_code                             character varying (5)
,agency                                  character varying (64)
,site_identification_number              character varying (15)
,monitoring_location_identifier          character varying(21)
,site_type_code                          character varying (7)
,site_type                               character varying (42)
,geom                                    geometry(point,4269)
,decimal_latitude                        decimal(17,14)
,decimal_longitude                       decimal(16,13)
,decimal_latitude_longitude_datum        character varying (255)
,well_depth                              character varying (8)
,hole_depth                              character varying (8)
,local_aquifer                           character varying (70)
,local_aquifer_type                      character varying (255)
,date_measured_raw                       timestamp
,timezone_code                           character varying (6)
,timezone_offset                         character varying (6)
,parameter_code                          character varying (5)
,date_measured                           character varying (10)
,time_measured_utc                       character varying (8)
,level_feet_below_land_surface           character varying (12)
,level_feet_above_vertical_datum         character varying (12)
,vertical_datum_code                     character varying (10)
,vertical_datum                          character varying (255)
,site_status_code                        character varying (1)
,site_status                             character varying (255)
,measuring_agency_code                   character varying (5)
,measuring_agency                        character varying (255)
,date_time_accuracy_code                 character varying (1)
,date_time_accuracy                      character varying (255)
,level_accuracy_code                     character varying (1)
,level_accuracy                          character varying (255)
,measurement_source_code                 character varying (1)
,measurement_source                      character varying (255)
,measurement_method_code                 character varying (1)
,measurement_method                      character varying (255)
,approval_status_code                    character varying (1)
,approval_status                         character varying (255)
,primary key (monitoring_location_id, date_measured_raw, date_time_accuracy_code, timezone_code)
) with (fillfactor = 100);
