create table int_qw_sample
(nwis_host_nm                   varchar2(42 char)
,db_no                          varchar2(6 char)
,record_no                      varchar2(24 char)
,agency_cd                      varchar2(15 char)
,site_no                        varchar2(45 char)
,site_db_no                     varchar2(6 char)
,medium_cd                      varchar2(9 char)
,sample_start_dt                timestamp(6)
,sample_start_sg                varchar2(3 char)
,sample_start_tz_cd             varchar2(18 char)
,sample_start_local_tm_fg       varchar2(3 char)
,sample_end_dt                  timestamp(6)
,sample_end_sg                  varchar2(3 char)
,sample_end_tz_cd               varchar2(18 char)
,sample_end_local_tm_fg         varchar2(3 char)
,sample_start_local_disp_fm     varchar2(57 char)
,sample_start_utc_disp_fm       varchar2(57 char)
,sample_end_local_disp_fm       varchar2(57 char)
,sample_end_utc_disp_fm         varchar2(57 char)
,local_tz_cd                    varchar2(18 char)
,tm_datum_rlblty_cd             varchar2(3 char)
,sample_id                      integer
,anl_stat_cd                    varchar2(3 char)
,hyd_cond_cd                    varchar2(3 char)
,samp_type_cd                   varchar2(3 char)
,hyd_event_cd                   varchar2(3 char)
,project_cd                     varchar2(27 char)
,aqfr_cd                        varchar2(24 char)
,lab_no                         varchar2(21 char)
,tu_id                          integer
,body_part_id                   integer
,coll_ent_cd                    varchar2(24 char)
,sidno_party_cd                 varchar2(9 char)
,sample_cn                      varchar2(312 char)
,sample_cr                      timestamp(6)
,sample_mn                      varchar2(312 char)
,sample_md                      timestamp(6)
,sample_lab_cm_tx               varchar2(4000 char)
,sample_lab_cm_cn               varchar2(312 char)
,sample_lab_cm_cr               timestamp(6)
,sample_lab_cm_mn               varchar2(312 char)
,sample_lab_cm_md               timestamp(6)
,sample_field_cm_tx             varchar2(4000 char)
,sample_field_cm_cn             varchar2(312 char)
,sample_field_cm_cr             timestamp(6)
,sample_field_cm_mn             varchar2(312 char)
,sample_field_cm_md             timestamp(6)
,sample_web_cd                  varchar2(3 char)
,deprecated_fg                  varchar2(3 char)
,sample_ld                      timestamp(6)
) parallel 4 compress pctfree 0 nologging;
