create table if not exists ${NWIS_SCHEMA_NAME}.groundwater_daily_value
(groundwater_daily_value_id              integer generated by default as identity (start with 1)
,groundwater_daily_value_identifier      character varying (54)
,time_series_unique_id                   character varying (32)
,monitoring_location_id                  integer
,monitoring_location_identifier          character varying (21)
,geom                                    geometry (point,4269)
,observered_property_id                  character varying (5)
,observered_property_name                text
,observered_property_reference           text
,sampling_feature_name                   character varying (50)
,statistic_id                            character varying (5)
,statistic                               text
,statistic_reference                     text
,time_step                               date
,unit_of_measure_id                      text
,unit_of_measure                         text
,unit_of_measure_reference               text
,result                                  text
,nil_reason                              text
,approvals                               text
,qualifiers                              text
,grades                                  text
,primary key (groundwater_daily_value_id)
)
